apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
type: Opaque
stringData:
  database: {{ .Values.postgres.database | quote }}
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
