name: CD Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BACKEND_IMAGE: mkr05/hello-world-devops-backend
  FRONTEND_IMAGE: mkr05/hello-world-devops-frontend

jobs:

  docker-release:
    name: Docker Build, Scan, Push & Manifest Update
    runs-on: [self-hosted, runner-1]

    defaults:
      run:
        shell: cmd

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u %DOCKER_USERNAME% -p %DOCKER_PASSWORD%

      - name: Set Image Tag
        run: echo IMAGE_TAG=%GITHUB_SHA:~0,7%>>%GITHUB_ENV%



      - name: Build Backend Image
        run: docker build -t %BACKEND_IMAGE%:%IMAGE_TAG% .

      - name: Scan Backend Image
        run: docker scout cves %BACKEND_IMAGE%:%IMAGE_TAG%

      - name: Push Backend Image
        run: docker push %BACKEND_IMAGE%:%IMAGE_TAG%



      - name: Build Frontend Image
        run: docker build -t %FRONTEND_IMAGE%:%IMAGE_TAG% ./frontend

      - name: Scan Frontend Image
        run: docker scout cves %FRONTEND_IMAGE%:%IMAGE_TAG%

      - name: Push Frontend Image
        run: docker push %FRONTEND_IMAGE%:%IMAGE_TAG%



      - name: Update Helm Image Tags
        run: |
          powershell.exe -ExecutionPolicy Bypass -Command ^
          "$file='helm/hello-world-devops/values.yaml'; ^
          $content=Get-Content $file -Raw; ^
          $content=$content -replace '(?m)^(\s*backend:\s*\r?\n\s*image:\s*\r?\n\s*repository:.*\r?\n\s*tag:\s*)[^\r\n]+$', '${1}' + [char]34 + $env:IMAGE_TAG + [char]34; ^
          $content=$content -replace '(?m)^(\s*frontend:\s*\r?\n\s*image:\s*\r?\n\s*repository:.*\r?\n\s*tag:\s*)[^\r\n]+$', '${1}' + [char]34 + $env:IMAGE_TAG + [char]34; ^
          [System.IO.File]::WriteAllText($file, $content)"

      - name: Commit Helm Update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/hello-world-devops/values.yaml

          git commit -m "Update image tags to %IMAGE_TAG% [skip ci]" || echo No changes to commit

          git pull --rebase origin main

          git push origin main