name: CI Pipeline

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Job
    runs-on: self-hosted

    env:
      GIT_CONFIG_COUNT: 1
      GIT_CONFIG_KEY_0: core.autocrlf
      GIT_CONFIG_VALUE_0: false

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Node.js
        run: node --version

      - name: Check npm
        run: npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Unit Test
        run: npm test

      - name: Biome Format
        run: npx biome format . --write

      - name: Biome Check
        run: npm run format:check

      - name: ESLint
        run: npm run lint